---
ds-ansible-worker:
  scale: 2
  health_check:
    port: 8083
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    request_line: GET "/health" "HTTP/1.0"
    healthy_threshold: 2