---
name: RDBS Minion Listener
description: Minion routing system - receiver
version: 0
category: rdbs
maintainer: steven.tarver@ctl.io
license: None
projectURL: https://github.com/CenturyLinkCloud/ds-minion-listener